# permissions for end users to view trafficstats.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: trafficstat-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: knative-hybrid-scaling
    app.kubernetes.io/part-of: knative-hybrid-scaling
    app.kubernetes.io/managed-by: kustomize
  name: trafficstat-viewer-role
rules:
- apiGroups:
  - hybridscaling.knativescaling.dcn.ssu.ac.kr
  resources:
  - trafficstats
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hybridscaling.knativescaling.dcn.ssu.ac.kr
  resources:
  - trafficstats/status
  verbs:
  - get
